name: CI with GitHub Actions using Maven and JUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn -B clean package

      - name: Run JUnit tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Distribute jar file
        run: mkdir staging && cp target/*.jar staging

      - name: Make hyperlink to jar file
        uses: actions/upload-artifact@v2
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging
